# netlify.toml

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Additional custom redirects can go here.
# Just be careful not to interfere with the Next.js pages and API routes.
# For example:
# Redirect from old page to new page permanently (HTTP 301)
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

# Redirect from all URLs within an old directory to a new directory (wildcard syntax)
[[redirects]]
  from = "/old-directory/*"
  to = "/new-directory/:splat"
  status = 301
